### PR TITLE
[CMake] Add missing link

### PR DESCRIPTION
**Pull request by jmirabel**

### CODE REVIEW

**Comment by jmirabel** [comment]
@nim65s is everything working fine for you without this ?

I get compilation errors because roboptim headers (in /opt/openrobots/include) are not found. This is because dependency between hpp-walkgen library and roboptim was not exportable.

**Comment by nim65s** [comment]
yes, it is working fine for me without this modification. And I don't understand the relation between your commit and roboptim.

I am still using `PKG_CONFIG_USE_DEPENDENCY` here, and here is what is found on my system with roboptim-core & trajectory installed from robotpkg binaries:

```
╰─>$ grep ROBOPTIM config.log 
ROBOPTIM_TRAJECTORY_FOUND = 1
ROBOPTIM_TRAJECTORY_LIBRARIES = roboptim-trajectory;roboptim-core;ltdl;log4cxx
ROBOPTIM_TRAJECTORY_LIBRARY_DIRS = /opt/openrobots/lib
ROBOPTIM_TRAJECTORY_LDFLAGS = -L/opt/openrobots/lib;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-trajectory;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-core;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-lltdl;-llog4cxx
ROBOPTIM_TRAJECTORY_LDFLAGS_OTHER = -Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu
ROBOPTIM_TRAJECTORY_INCLUDE_DIRS = /opt/openrobots/include;/usr/include/eigen3
ROBOPTIM_TRAJECTORY_CFLAGS = -DROBOPTIM_DO_NOT_CHECK_ALLOCATION;-DROBOPTIM_STORAGE_ORDER=ColMajor;-I/opt/openrobots/include;-I/usr/include/eigen3
ROBOPTIM_TRAJECTORY_CFLAGS_OTHER = -DROBOPTIM_DO_NOT_CHECK_ALLOCATION;-DROBOPTIM_STORAGE_ORDER=ColMajor
ROBOPTIM_TRAJECTORY = undefined
ROBOPTIM_TRAJECTORY_STATIC = undefined
ROBOPTIM_TRAJECTORY_VERSION = 3.1
ROBOPTIM_TRAJECTORY_PREFIX = /opt/openrobots
ROBOPTIM_TRAJECTORY_INCLUDEDIR = /opt/openrobots/include
ROBOPTIM_TRAJECTORY_LIBDIR = /opt/openrobots/lib
ROBOPTIM_TRAJECTORY_PKGLIBDIR = /opt/openrobots/lib/roboptim-trajectory
ROBOPTIM_TRAJECTORY_BINDIR = /opt/openrobots/bin
ROBOPTIM_TRAJECTORY_DATAROOTDIR = /opt/openrobots/share
ROBOPTIM_TRAJECTORY_PKGDATAROOTDIR = /opt/openrobots/share
ROBOPTIM_TRAJECTORY_DOCDIR = /opt/openrobots/share/doc/roboptim-trajectory
ROBOPTIM_TRAJECTORY_DOXYGENDOCDIR = /opt/openrobots/share/doc/roboptim-trajectory/doxygen-html
```

**Comment by nim65s** [comment]
I would understand configuration errors, but compilations ? Is your `ROBOPTIM_TRAJECTORY_INCLUDEDIR` correct ?

**Comment by nim65s** [comment]
Moreover, do you have this issue when configuring/compiling this package, or a dependent one ?

**Comment by jmirabel** [comment]
I have the issue when compiling the unit test and when compiling hpp-wholebody-step. At first, I did https://github.com/humanoid-path-planner/hpp-walkgen/commit/a41c886c8a3ba6d101c77ad457e0034d1f578d1f to fix the unit test but then, I realized the real issue.

If you look at the generate Target.cmake file, do you have stuff related to roboptim ? I think you don't, while you should have. At least, without this, I don't.

**Comment by jmirabel** [comment]
when using this commit, the set_target_properties in targets.cmake is:
```cmake
set_target_properties(hpp-walkgen::hpp-walkgen PROPERTIES
  INTERFACE_COMPILE_OPTIONS "-DROBOPTIM_DO_NOT_CHECK_ALLOCATION;-DROBOPTIM_STORAGE_ORDER=ColMajor"
  INTERFACE_INCLUDE_DIRECTORIES "/opt/openrobots/include;/usr/include/eigen3"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;hpp-core::hpp-core;-L/opt/openrobots/lib;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-trajectory;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-core;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-lltdl;-llog4cxx;-Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu"
  INTERFACE_SYSTEM_INCLUDE_DIRECTORIES "/opt/openrobots/include;/usr/include/eigen3"
)
```

**Comment by nim65s** [comment]
I can compile and run tests. 

I have 
```
╰─>$ grep -i roboptim /tmp/toto/lib/cmake/hpp-walkgen/hpp-walkgenTargets.cmake
  INTERFACE_COMPILE_OPTIONS "-DROBOPTIM_DO_NOT_CHECK_ALLOCATION;-DROBOPTIM_STORAGE_ORDER=ColMajor"
  INTERFACE_LINK_LIBRARIES "/usr/lib/x86_64-linux-gnu/libboost_filesystem.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_program_options.so;/usr/lib/x86_64-linux-gnu/libboost_unit_test_framework.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;hpp-core::hpp-core;-L/opt/openrobots/lib;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-trajectory;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-lroboptim-core;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-lltdl;-llog4cxx;-Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu;-Wl,-rpath,/opt/openrobots/lib;-Wl,-rpath,/usr/lib/x86_64-linux-gnu"
```

So there his nothing about the headers. which are in my case in `/opt/openrobots/include`. And if I look for `openrobots`, I only have `/opt/openrobots/lib` stuff.

Then, I'm starting to understand why this is not working for you, but I don't understand why this is working for me…

**Comment by nim65s** [comment]
in `[ 80%] Building CXX object tests/CMakeFiles/twenty-steps.dir/twenty-steps.cc.o`, I have `-isystem /opt/openrobots/include`, but I don't know where this comes from.

**Comment by nim65s** [comment]
Maybe this is comming from qpOASES on my side ? Don't you have qpOASES from robotpkg and in /opt/openrobots ?

**Comment by jmirabel** [comment]
hpp-constraints is compiled without on my computer.

**Comment by nim65s** [comment]
Now I can reproduce. It took me way more time to understand that it should have, sorry.

**Pull request merged**
