### PR TITLE
Use roboptim v3.1, fix #4

### LINKED ISSUE #4: Minimum roboptim required version
Hi,

The commit 4968aa2b4de12d3b5226574243d16d6309062297 refers to `basisPolynomialsVector_t`, which was added in roboptim-trajectory in v3.2

I therefore suggest to update the requirement in the CMakeFile accordingly.

This will delay https://github.com/humanoid-path-planner/hpp-doc/issues/23 a bit, as robotpkg has v3.1, but I can update it too.

### PR DESCRIPTION
**Pull request by nim65s**
Hi,

Trying to fix https://github.com/humanoid-path-planner/hpp-doc/issues/23 I found that this repo had been updated to use roboptim v3.2, but roboptim v3.2 doesn't work on ubuntu xenial 16.04.

I therefore reverted those changes. 

While here, I set up gitlab-CI

### CODE REVIEW

**Comment by florent-lamiraux** [comment]
After the release, can you revert this change since the current version is compatible with the master branch of roboptim-core.

**Comment by nim65s** [comment]
If we want the releases to be compatibles with the releases, and master to be compatible with master, I think it would be better to write one code that is compatible with both 3.1 and master

**Comment by florent-lamiraux** [comment]
Good idea, can you do it ?

**Comment by nim65s** [comment]
I will try

**Pull request closed without merging**
